# Generated by Django 4.0.3 on 2022-04-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.DecimalField(decimal_places=3, max_digits=10)),
                ('close', models.DecimalField(decimal_places=3, max_digits=10)),
                ('low', models.DecimalField(decimal_places=3, max_digits=10)),
                ('high', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
